import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NextAuthSessionProvider } from "@/context/SessionProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import {
  ClerkProvider,
  SignIn,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header className="w-full h-14 border-b flex justify-end items-center px-16 py-6">
            <SignedOut>
              <Link href={"/sign-in"}>SignIn</Link>
              {/* <SignInButton /> */}
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </header>
          <main className="flex flex-col justify-center min-h-svh items-center">
            <SignedOut>
              <SignIn
                routing="hash"
                signUpUrl="/sign-up"
                signInUrl="/sign-in"
              />
            </SignedOut>
            <SignedIn>
              {/* <NextAuthSessionProvider session={session}> */}
              {children}
            </SignedIn>
          </main>
          {/* </NextAuthSessionProvider> */}
        </body>
      </html>
    </ClerkProvider>
  );
}
